### ISSUE TITLE
[Enhancement] Updating citation DB

### ISSUE THREAD

**Issue by andupaz** [sawhney17/logseq-citation-manager#29]
Doing research, adding literature to Zotero and quickly wanting to open them in Logseq made me realise that the citation DB is not up to date/is "fixed" to the bibtex file version when Logseq was opened/plugin was first started. I have to disable and enable the plugin for it to update. Is there a way to update it without having to disable/enable the plugin? I read I can force reindex through command pallette - would that solve it and where do I find it?

**Comment by s-kyy** [comment]
Hi, were you able to resolve this? What have you been able to do?

To @sawhney17 , I would still like a function in the command palette to manually refresh the database when I need to instead of:

- Disabling / enabling the plugin (as @andupaz mentioned)
- closing and reopening logseq (refresh / re-index doesn't work for me)

Please let me know if I missed something obvious, and thank you for your time. 

Logseq: 0.8.18
OS: Windows 10

**Comment by sawhney17** [comment]
This functionality should la read work. For refresh you should use th function reindex citation db in the command palette

**Comment by s-kyy** [comment]
Yes, I was able to figure it out from the readme after going through it
again (made an edit on my original post earlier), Thank you for the extra
tip about the function as well.
